package com.web.hackaton.exception;

import org.springframework.boot.web.servlet.error.DefaultErrorAttributes;
import org.springframework.boot.web.servlet.error.ErrorAttributes;
import org.springframework.context.annotation.Bean;
import org.springframework.http.HttpStatus;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;
import org.springframework.web.context.request.WebRequest;

import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.Map;

@RestControllerAdvice
public class GlobalExceptionHandlerController {

    @Bean
    public ErrorAttributes errorAttributes() {
        return new DefaultErrorAttributes() {
            @Override
            public Map<String, Object> getErrorAttributes(final WebRequest webRequest, final boolean includeStackTrace) {
                final Map<String, Object> errorAttributes = super.getErrorAttributes(webRequest, includeStackTrace);
                errorAttributes.remove("exception");
                return errorAttributes;
            }
        };
    }

    @ExceptionHandler(CustomException.class)
    public void handleCustomException(final HttpServletResponse res, final CustomException ex) throws IOException {
        res.sendError(ex.getHttpStatus().value(), ex.getMessage());
        ex.printStackTrace();
    }

    @ExceptionHandler(AccessDeniedException.class)
    public void handleAccessDeniedException(final HttpServletResponse res) throws IOException {
        res.sendError(HttpStatus.FORBIDDEN.value(), "Access denied");
    }

    @ExceptionHandler(Exception.class)
    public void handleException(final HttpServletResponse res, final Exception ex) throws IOException {
        res.sendError(HttpStatus.BAD_REQUEST.value(), "Something went wrong");
        ex.printStackTrace();
    }

    @ExceptionHandler(SingInException.class)
    public void handleSingInException(final HttpServletResponse res, final CustomException ex) throws IOException {
        res.sendError(ex.getHttpStatus().value(), ex.getMessage());
        ex.printStackTrace();
    }
}
